#!/bin/bash -x
(
WRK_MGR_DIR=$(dirname $(readlink -f ${0}))
. ${WRK_MGR_DIR}/functions
printf "$(now) WRK_MGR_DIR=${WRK_MGR_DIR}\n"
printf "$(now) WRK_REPO_PATH=${WRK_REPO_PATH}\n"
printf "$(now) WRK_REPOS=${WRK_REPO_LIST}\n"
printf "$(now) WRK_STEPS=${WRK_REPO_STEPS}\n"
printf "$(now) WRK_STEP_RETRIES=${WRK_STEP_RETRIES}\n"
printf "$(now) WRK_STATUS_PATH=${WRK_STATUS_PATH}\n"

printf "$(now) Step ${WRK_STEP} sleep for 1 second intervals.\n"
cd ${WRK_REPO_PATH}
for repo in ${WRK_REPOS}; do
    mkdir -p ${repo};
    cd ${WRK_REPO_PATH}/${repo};
    ( ./prepare.sh ) &> ${repo##*/}.repo-prepare.log &
done
wait
# Exercise a wait loop sleeping for one second intervals
for (( c=0; c<${WRK_STEPS}; c++)); do
    printf "$(now) unlock step ${WRK_STEP}.\n"
    # . ${WRK_MGR_DIR}/current-step
    step=$(printf "step-%02d" ${c})
    WRK_STEP_START=${WRK_STATUS_PATH}/${step}.start
    WRK_STEP_DONE=${WRK_STATUS_PATH}/${step}.done
    WRK_STEP_ERROR=${WRK_STATUS_PATH}/${step}.error
    printf "$(now) WRK_STEP_START=${WRK_STEP_START}\n"
    printf "$(now) WRK_STEP_DONE=${WRK_STEP_DONE}\n"
    printf "$(now) WRK_STEP_ERROR=${WRK_STEP_ERROR}\n"
    start=${WRK_STEP_START}
    complete=${WRK_STEP_DONE}
    error=${WRK_STEP_ERROR}
    printf "$(now) creating ${start}\n"
    touch ${start}
    for ((i=0; i<${WRK_STEP_RETRIES}; i++)); do
        printf "$(now) retry ${i} waiting for file ${complete} or ${error}. Sleeping for 1 second intervals.\n"
        for ((s=0; s<60; s++)); do
            if [[ -e "${complete}" ]]; then break; fi
            if [[ -e "${error}" ]]; then break; fi
            printf "."
            sleep 1
        done
        if [[ -e "${complete}" ]]; then break; fi
        if [[ -e "${error}" ]]; then break; fi
        printf "\n"
    done
    if [[ -e "${error}" ]]; then break; fi
done
for repo in ${WRK_REPOS}; do
    cd ${WRK_REPO_PATH}/${repo}
    ( ./cleanup.sh ) &> ${repo##*/}.repo-cleanup.log &
done
) > ${WRK_STATUS_PATH}/${WRK_STEP}.status 2>&1
